environment: production
chdir: /home/ec2-user/www/app/current/
address: 127.0.0.1
user: ec2-user
group: ec2-user
port: 8000
pid: /tmp/thin.pid
rackup: /home/ec2-user/www/app/current/config.ru
log: /home/ec2-user/www/app/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true